# Generated by Django 3.1 on 2020-10-04 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='code_field',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
