# Generated by Django 3.1 on 2020-10-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_mymodel_code_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='myfield',
        ),
    ]
